queue_rules:
  - name: default
    batch_size: 1
    queue_conditions:
      - base=main
      - label="merge-when-passing"
      - label!="work-in-progress"
      - -title~=^\[*[Ww][Ii][Pp]
      - "approved-reviews-by=@flux-framework/core"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
    merge_conditions:
      - base=main
      - label="merge-when-passing"
      - label!="work-in-progress"
      - -title~=^\[*[Ww][Ii][Pp]
      - "approved-reviews-by=@flux-framework/core"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
    update_method: rebase
    merge_method: merge

# Avoid temporary branches created by mergify for parallel checks.
# These do not work with the pr-validator since the temporary PR
# branch is updated with a merge commit.
merge_queue:
  max_parallel_checks: 1

pull_request_rules:
  - name: rebase and merge when passing all checks
    conditions: []
    actions:
      queue:
